<?php

namespace App;

use Illuminate\Notifications\Notifiable;
use Illuminate\Foundation\Auth\User as Authenticatable;

class User extends Authenticatable
{
    use Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name', 'email', 'password',
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password', 'remember_token',
    ];

    public static function boot()
    {
        parent::boot(); // TODO: Change the autogenerated

        static::creating(function ($user) {
            $user->token = str_random(60);
        });
    }

    public function applications($id_app)
    {
        return $this->belongsToMany('App\Application', 'state_uses', 'id_users', 'id_app')
            ->withPivot('timeUse', 'quantity', 'lastUseTime')
            ->wherePivot('id_app', $id_app);
    }
}
